### ISSUE TITLE
Library MD-Parola amd MD72XX 

### ISSUE THREAD

**Issue by pramodmadhav** [arduino/uno-r4-library-compatibility#23]
Compile pass
Test Pass

**Comment by Hannes7eicher** [comment]
Thank you for testing!

Added both here:
- https://github.com/arduino/uno-r4-library-compatibility/commit/9a8c241b93d6edc3c791761c0a595cf638053ecd
- https://github.com/arduino/uno-r4-library-compatibility/commit/445e644e21c9880e592d4e8f1a981b145d0cf09d
