### ISSUE TITLE
MobaTools compatible to UNO R4 from V2.6 on

### ISSUE THREAD

**Issue by MicroBahner** [arduino/uno-r4-library-compatibility#26]
Starting with V2.6 the [MobaTools library](https://github.com/MicroBahner/MobaTools) (Steppers with acceleration, slow moving Servos and more) is compatible with the new UNO R4.
Testing is always welcome ;)

**Comment by Hannes7eicher** [comment]
https://github.com/arduino/uno-r4-library-compatibility/commit/9a64eb76b882be8310813d3053beeb60d60b2ad8
