### ISSUE TITLE
USB Host Shield 2.0

### ISSUE THREAD

**Issue by mjs513** [arduino/uno-r4-library-compatibility#9]
Just Updated the library to support the Maxima and WiFi boards.  Issued a PR: https://github.com/felis/USB_Host_Shield_2.0/pull/779

My fork it currently updated and tested with the PS4 and XBOX controller sketches:  https://github.com/mjs513/USB_Host_Shield_2.0

not sure I should also add this to the forum.  Your call.

Without the changes compile and run both fail.

**Comment by Hannes7eicher** [comment]
Apologies for the extremly late answer! I've now added the library to the USB section. If you haven't already feel free to add your fix to the forum as well, and thank you very much for the migration work!

https://github.com/arduino/uno-r4-library-compatibility/commit/050125bb43bb96c9c0dc7f135c7c9986fe0393d7
